### ISSUE TITLE
Setup docker-compose environment

### ISSUE THREAD

**Issue by mwalbeck** [MetaProvide/nextcloud-swarm-plugin#13]

**Comment by mwalbeck** [comment]
```
---
version: '2'

volumes:
  mariadb:
  nextcloud:

networks:
  frontend:
  backend:

services:
  mariadb:
    image: mariadb:10.5
    restart: on-failure:5
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD_HERE

  nextcloud:
    image: mwalbeck/nextcloud-metaprovide:23
    restart: on-failure:5
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    volumes:
      - nextcloud:/var/www/html
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_HOST: mariadb:3306
      NEXTCLOUD_ADMIN_USER: test
      NEXTCLOUD_ADMIN_PASSWORD: test

  nginx:
    image: nginx:1.20
    restart: on-failure:5
    user: "1000:1000"
    read_only: true
    security_opt:
      - no-new-privileges
    networks:
      - frontend
    volumes:
      - nextcloud:/var/www/html
```

**Comment by frozenbanana** [comment]
In addition we need a swarm node: https://hub.docker.com/r/ethersphere/bee

**Comment by frozenbanana** [comment]
draft of our service would append to snippet above: 
```
    swarm-node:
             image: ethersphere/bee:latest
    restart: on-failure:5
    networks:
      - backend
    volumes:
      - xxx:yyyy
```
